version: '2'
services:
  web:
    build: .
    ports:
     - "8002:8000"
    volumes:
     - .:/code
    env_file:
        - ".env"
  mysqldb:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "8989:3306"
